### ISSUE TITLE
Global todo list

### ISSUE THREAD

**Issue by EvertX** [EvertX/IntoTheForest#1]
- [ ] Make it work on servers/multiplayer (never done this, need help)
- [ ] Check and change IE recipes (and some Animania?)
- [ ] Clean-up and restructure Scripts
- [ ] Cave-ins (need a modder for this)
- [ ] Get rid of the "Object successfully summoned" messages (how do I change a gamerule on world-creation?)
